apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: allow-external-egress
    namespace: default
spec:
    podSelector:
        matchLabels:
            app: nanumsa-api-server
    policyTypes:
        - Ingress
        - Egress
    egress:
        - to:
              - ipBlock:
                    cidr: 0.0.0.0/0
