apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
commonLabels:
  app: nanumsa-api-service

images:
- name: smilemeeso/
  newTag: 0.1.0
- name: smilemeeso/nanumsa-api-service

resources:
- ./deployment.yaml
- ./service.yaml
- ./ingress.yaml
commonAnnotations:
  version: 0.1.0
