apiVersion: v1
kind: Service
metadata:
    name: nanumsa-api-server
spec:
    type: ClusterIP
    selector:
        app: nanumsa-api-server
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080