apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nanumsa-socket-server
  name: nanumsa-socket-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanumsa-socket-server
  template:
    metadata:
      labels:
        app: nanumsa-socket-server
    spec:
      containers:
      - image: smilemeeso/nanumsa-socket-server:0.1.34
        name: nanumsa-socket-server
        ports:
        - containerPort: 3000
