apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: default
data:
  add-headers: application/json
  allowSnippetAnnotations: "true"
  annotations-risk-level: Critical
  default-type: application/json
  externalAuth: "false"
  additional-headers: "X-Frame-Options: SAMEORIGIN"
  types: |
    application/json json
    application/javascript js
    application/javascript ts
    application/css css
    text/css css


# helm upgrade nanumsa-ingress ingress-nginx/ingress-nginx \
# --set controller.configMap.name=nginx-configuration

# kubectl delete pod -l app.kubernetes.io/name=ingress-nginx -n ingress-nginx
