apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nanumsa-socket-server-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-set-headers: '{"X-Forwarded-Proto": "ws"}'
    nginx.ingress.kubernetes.io/websocket-services: "nanumsa-socket-server"
    nginx.ingress.kubernetes.io/upgrade: "websocket"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, DELETE, PATCH, PUT, OPTIONS
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass_header Content-Type;
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /socket
        pathType: Prefix
        backend:
          service:
            name: nanumsa-socket-server
            port:
              number: 3000
