apiVersion: apps/v1
kind: Deployment
metadata:
    name: nanumsa-front
    annotations:
      version: "0.0.0"
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nanumsa-front
    template:
        metadata:
            labels:
                app: nanumsa-front
        spec:
            containers:
                - name: nanumsa-front
                  image: smilemeeso/nanumsa-fe:latest
                  ports:
                      - containerPort: 80
