apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    version: 0.1.0
  labels:
    app: nanumsa-front
  name: nanumsa-front
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanumsa-front
  template:
    metadata:
      annotations:
        version: 0.1.0
      labels:
        app: nanumsa-front
    spec:
      containers:
        - image: smilemeeso/nanumsa-front:latest
          name: nanumsa-front
          ports:
            - containerPort: 80
