apiVersion: apps/v1
kind: Deployment
metadata:
    name: nanumsa-front
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nanumsa-front
    template:
        metadata:
            labels:
                app: nanumsa-front
        spec:
            containers:
                - name: nanumsa-front
                  image: nanumsa-front:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 80
