apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nanumsa-front
commonLabels:
  app: nanumsa-front

images:
  - name: smilemeeso/nanumsa-fe

resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml
